apiVersion: v1
kind: Service
metadata:
  name: shibboleth-service
spec:
  selector:
    app: shibboleth
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
      nodePort: 30443
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
      nodePort: 30080
  type: LoadBalancer  # Use the appropriate service type for your environment
