apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../demo
  - minio-standalone

resources:
  - secrets.yaml

patchesStrategicMerge:
  - configmap.yaml
  - patch-pod-s3-secret.yaml
  - patch-memory.yaml
