---
apiVersion: v1
kind: Secret
metadata:
  name: dataverse-s3
  labels:
    app.kubernetes.io/name: dataverse-s3
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  access-key: dataverse
  secret-key: changeme
