---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  namespace: dv-test
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
