---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../demo
  - github.com/rancher/local-path-provisioner/deploy

resources:
  - ingress.yaml

patches:
  - patch-pvc-k3s.yaml
