---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../demo
  - github.com/poikilotherm/local-path-provisioner/deploy?ref=feature-kustomize-support

resources:
  - ingress.yaml

patches:
  - patch-pvc-k3s.yaml
