apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql
  - ../../k8s
  - ../../k8s/dataverse/jobs
  - ../secrets/secrets.yaml
  - mailcatcher.yaml
  - configmap.yaml

patchesStrategicMerge:
  - patch-memory.yaml
