apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - k8s/utils/postgresql
  - k8s/solr
  - k8s/dataverse

resources:
  - k8s/utils/demo-secrets.yaml

images:
  - name: iqss/dataverse-k8s
    newTag: "4.16"
  - name: iqss/solr-k8s
    newTag: "4.16"
