apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: iqss/dataverse-k8s
    context: .
    docker:
      dockerfile: docker/dataverse-k8s/glassfish-dev/Dockerfile
  - image: iqss/solr-k8s
    context: docker/solr-k8s
  local: {}
deploy:
  kustomize: {}
