#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: dv-test-nfs-pv
#spec:
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: nfs-storage
#  nfs:
#    path: /exports
#    server: 192.168.178.20 # Use your Windows IP here


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dv-test-nfs-pv
  namespace: test-space
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
