---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - svc.yaml
#  - ing.yaml

images:
  - name: iqss/dataverse-k8s
    newTag: "tt"
#    newTag: "4.20-payara"
