---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  storageClassName: gp2
  selector:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataverse-files
spec:
  storageClassName: gp2
  selector:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataverse-docroot
spec:
  storageClassName: gp2
  selector:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: solr
spec:
  storageClassName: gp2
  selector:
