---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  # storageClassName: pm-local
