---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataverse
  labels:
    app: dataverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataverse
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: dataverse
      annotations: {}
    spec:
      containers:
        - name: dataverse
          image: iqss/dataverse-k8s
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dataverse
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {} # TODO: this needs to be replaced by a PVC!!!
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dataverse
  labels:
    app: dataverse
data:
  HOST_DNS_ADDRESS: localhost
  MAIL_SERVER: postfix
  POSTGRES_SERVER: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: dvndb
  POSTGRES_USER: dvnapp
---
kind: Service
apiVersion: v1
metadata:
  name: dataverse
spec:
  ports:
    - port: 8080
      name: dataverse-http
      targetPort: 8080
      protocol: TCP
    - port: 8009
      name: dataverse-ajp
      targetPort: 8009
      protocol: TCP
  selector:
    app: dataverse
