apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - postgresql
  - ../../k8s
  - ../../k8s/dataverse/jobs

resources:
  - secrets.yaml
  - mailcatcher.yaml

images:

patchesStrategicMerge:
  - configmap.yaml
  - patch-memory.yaml
