---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/IQSS/dataverse-kubernetes/personas/demo/postgresql?ref=v4.20

patchesStrategicMerge:
  - patch-pvc.yaml
  - patch-limits.yaml
