---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataverse-files
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dataverse-docroot
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

