---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dataverse
  labels:
    app: dataverse
    app.kubernetes.io/name: configmap
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
data:
  ### GENERAL SETTINGS
  dataverse_fqdn: "141.19.44.18:8080"
  dataverse_siteUrl: "http://141.19.44.18:8080"

  ### database
  POSTGRES_ONLY: "true"
  POSTGRES_SERVER: "postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: "mydataverse"
  POSTGRES_USER: "dataverse"
  POSTGRES_PASSWORD: "POSTGRES_PASSWORD"
  dataverse_db_password: "dataverse_db_password"


  ### CONTACT SETTINGS
  CONTACT_MAIL: CONTACT_MAIL
  MAIL_FROMADDRESS: MAIL_FROMADDRESS
  DATAVERSE_MAIL_SYSTEM_EMAIL: DATAVERSE_MAIL_SYSTEM_EMAIL
  DATAVERSE_MAIL_SYSTEM_EMAIL: DATAVERSE_MAIL_SYSTEM_EMAIL
  MAIL_SERVER: MAIL_SERVER

  DATAVERSE_MAIL_SYSTEM__EMAIL: HyperSpecFDM <DATAVERSE_MAIL_SYSTEM__EMAIL>
  DATAVERSE_MAIL_MTA_HOST: DATAVERSE_MAIL_MTA_HOST
  DATAVERSE_MAIL_MTA_PORT: "465"
  DATAVERSE_MAIL_MTA_SSL_ENABLE: "true"
  DATAVERSE_MAIL_MTA_AUTH: "true"
  DATAVERSE_MAIL_MTA_USER: DATAVERSE_MAIL_MTA_USER
  DATAVERSE_MAIL_MTA_ALLOW_UTD__8__ADDRESSES: "true"

  ## Updated DOI SETTINGS due to Dataverse Version 6.2
  dataverse_pid_providers: "fake"
  dataverse_pid_default__provider: "fake"
  dataverse_pid_fake_type: "FAKE"
  dataverse_pid_fake_label: "FakeDOIProvider"
  dataverse_pid_fake_authority: "10.5072"
  dataverse_pid_fake_shoulder: "FK2/"


  ### INGEST
  # deactivate ingest for tabular files
  db_TabularIngestSizeLimit: "0"
  # allow uploads only < 2GB
  db_MaxFileUploadSizeInBytes: "2147483648"
  db_FileFixityChecksumAlgorithm: SHA-256