---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dataverse
  labels:
    app: dataverse
    app.kubernetes.io/name: configmap
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: configmap
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
data:
  ### GENERAL SETTINGS
  dataverse_fqdn: 141.19.44.18
  dataverse_siteUrl: https://141.19.44.18

  ### database
  POSTGRES_ONLY: "true"
  POSTGRES_SERVER: postgresql
  POSTGRES_PORT: "5432"
  POSTGRES_DATABASE: mydataverse
  POSTGRES_USER: dataverse

  ### CONTACT SETTINGS
  CONTACT_MAIL: t.haeussermann@hs-mannheim.de
  MAIL_FROMADDRESS: t.haeussermann@hs-mannheim.de
  DATAVERSE_MAIL_SYSTEM_EMAIL: t.haeussermann@hs-mannheim.de
  DATAVERSE_MAIL_SUPPORT_EMAI: t.haeussermann@hs-mannheim.de
  DATAVERSE_MAIL_DEBUG: "true"
  MAIL_SERVER: mail.hs-mannheim.de
  dataverse_mail_system-email: HyperSpecFDM <t.haeussermann@hs-mannheim.de>
  dataverse_mail_mta_host: mail.hs-mannheim.de
  dataverse_mail_mta_port: "465"
  dataverse_mail_mta_ssl_enable: "true"
  dataverse_mail_mta_auth: "true"
  dataverse_mail_mta_user: t.haeussermann@hs-mannheim.de

  ### DOI SETTINGS
  db_DoiProvider: FAKE
  db_Protocol: doi
  db_Authority: "10.12345"
  db_Shoulder: EXAMPLE/


  ### FILE STORAGE Local
#  dataverse_files_file_label: file
#  dataverse_files_file_type: file
#  dataverse_files_file_directory: /data
#  dataverse_files_storage__driver__id: file

  ## FILE STORAGE S3
#  dataverse_files_hsma_label: hsma
#  dataverse_files_hsma_type: s3
#  dataverse_files_hsma__custom__endpoint__url: http://minio:9000
#  dataverse_files_hsma__bucket__name: dataverse
#  # required for Minio!
#  dataverse_files_hsma__path__style__access: "true"

  ### INGEST
  # deactivate ingest for tabular files
  db_TabularIngestSizeLimit: "0"
  # allow uploads only < 2GB
  db_MaxFileUploadSizeInBytes: "2147483648"
  db_FileFixityChecksumAlgorithm: SHA-256

  ### CUSTOMIZATION
#  db_StatusMessageHeader: "Test Environment"
#  db_StatusMessageText: "<br />This instance is meant for testing, training and experiments. DOIs minted here are not citeable!"