---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: dataverse
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/part-of: dataverse
    spec:
      containers:
        - name: postgresql
          image: postgres:13.11 #9.6
          ports:
            - containerPort: 5432
          env:
            - name: PGUSER #POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: username
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB #PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: database
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: dataverse-postgresql
                  key: database
#          command:
#            - bash
#            - -c
#            - |
#              /docker-entrypoint.sh postgres &
#              until psql -U postgres -c '\l'; do
#                echo "PostgreSQL is unavailable. Waiting..."
#                sleep 1
#              done
#              psql -U postgres -c "CREATE USER $PGUSER WITH ENCRYPTED PASSWORD '$POSTGRES_PASSWORD';"
#              psql -U postgres -c "CREATE DATABASE $POSTGRES_DB;"
#              psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $PGUSER;"
#              psql -U $PGUSER -c "\connect $POSTGRES_DB"
#              echo "Initialization complete. PostgreSQL is ready to accept connections."
#              psql -U postgres -c "ALTER DATABASE $POSTGRES_DB OWNER TO $PGUSER;"
#              psql -U $PGUSER -d $POSTGRES_DB -c "SELECT version();"
#              sleep infinity
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql/data
              readOnly: false
          readinessProbe:
            exec:
              command: ["pg_isready"]
            initialDelaySeconds: 5
            failureThreshold: 100
            periodSeconds: 5
      volumes:
        - name: postgresql-persistent-storage
          persistentVolumeClaim:
            claimName: postgresql

