apiVersion: apps/v1
kind: Deployment
metadata:
  name: phppgadmin
  namespace: dv-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phppgadmin
  template:
    metadata:
      labels:
        app: phppgadmin
    spec:
      containers:
        - name: phppgadmin
          image: dpage/pgadmin4:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL #POSTGRES_USER
              value: user@domain.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: test
            - name: PGADMIN_DEFAULT_SERVER
              value: postgresql
            - name: PGADMIN_DEFAULT_PORT
              value: "5432"
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: phppgadmin-service
  namespace: dv-test
spec:
  selector:
    app: phppgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer