---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: solr
  labels:
    app.kubernetes.io/name: solr
    app.kubernetes.io/version: "9.3.0"
    app.kubernetes.io/component: searchindex
    app.kubernetes.io/part-of: dataverse
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: solr
      app.kubernetes.io/part-of: dataverse
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: solr
        app.kubernetes.io/part-of: dataverse
    spec:
      containers:
        - name: solr
          image: iqss/solr-k8s:9.3.0
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c", "$SCRIPT_DIR/schema/boot.sh"]
#          command: ["bash", "-c", "mkdir -p /var/solr/data/collection1 && precreate-core collection1 && solr -f -a \"-Dlog4j.configurationFile=/opt/solr-9.3.0/server/resources/log4j2.xml\""]
#          command: ["bash", "-c", "$SCRIPT_DIR/schema/createCollection.sh"]
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "4Gi"
          ports:
            - name: index
              containerPort: 8983
          volumeMounts:
#            - name: data
#              mountPath: /opt/solr/server/solr/collection1/data
            - name: data
              mountPath: /var/solr/data
            - name: schema
              mountPath: /schema
          env:
            - name: SOLR_PORT  # Otherwise, this is wrongfully set by K8s.
              value: "8983"
#            - name: SOLR_HOME
#              value: /opt/solr-9.3.0/server/solr/collection1/conf
            - name: SOLR_SECURITY_MANAGER_ENABLED
              value: "false"
            - name: SOLR_CORES
              value: "collection1"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 4 # thus restart after 4 minutes n/a
            httpGet:
              path: /solr/admin/info/system #/solr/collection1/admin/ping
              port: index
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 2
            httpGet:
              path: /solr/admin/info/system #/solr/collection1/admin/ping #./opt/solr-8.11.1/server/solr/collection1
              port: index
        - name: schema-sidecar
          image: iqss/solr-k8s:9.3.0
          imagePullPolicy: IfNotPresent
#          command: ["/tini", "--", "/scripts/schema/sidecar.sh"]
#          command: ["tini", "--", "sleep", "3600"]
#          command: ["tini", "--", "bash", "-c", "cd /scripts/schema && ./sidecar.sh"]
          command: ["tini", "--", "bash", "-c", "cd $SCRIPT_DIR/schema && ./sidecar.sh"]
          ports:
            - name: webhook
              containerPort: 9000
          volumeMounts:
            - name: schema
              mountPath: "/schema"
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 2
            httpGet:
              path: /
              port: webhook
#      imagePullSecrets:
#        - name: registry-auth
      initContainers:
        - name: volume-mount-hack
          image: giantswarm/tiny-tools:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -c 8983:8983 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
        - name: schema-init
          image: iqss/solr-k8s:9.3.0
          imagePullPolicy: IfNotPresent
          command: ["/scripts/schema/init.sh"]
          volumeMounts:
            - name: schema
              mountPath: /schema
            - name: api-secret
              mountPath: "/scripts/schema/api"
              readOnly: true
#        - name: collection-init
#          image: iqss/solr-k8s:9.3.0
#          imagePullPolicy: IfNotPresent
#          command: ["bash", "-c", "mkdir /var/solr/data && precreate-core collection1 server/solr/collection1/conf" ]
#          env:
#            - name: SOLR_PORT  # Otherwise, this is wrongfully set by K8s.
#              value: "8983"
#            - name: SOLR_HOME
#              value: server/solr/collection1/conf
#            - name: SOLR_SECURITY_MANAGER_ENABLED
#              value: "false"
#            - name: SOLR_CORES
#              value: "collection1"
#          volumeMounts:
#            - name: data
#              mountPath: /opt/solr/server/solr/collection1/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: solr
        - name: schema
          emptyDir: {}
        - name: api-secret
          secret:
            secretName: dataverse-api
