---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - svc.yaml

images:
  - name: iqss/solr-k8s
    newTag: "8.11.1"
#    newTag: "tt"
#    newTag: "4.20"
